---
title: "Getting and Cleaning Data Project: Code Book"
output: html_document
---

## The Dataset

See README for more information on the data.


## The transformation

1. Extract only the measurements on the mean and standard deviation for each measurement.
2. Label the data set with descriptive variable names.
3. Use descriptive activity names to name the activities in the data set.
4. Merge the training and the test sets to create one data set.
5. Create a second, independent tidy data set with the average of each variable for each activity and each subject.



## The Variables

#Activities:

1 WALKING
2 WALKING_UPSTAIRS
3 WALKING_DOWNSTAIRS
4 SITTING
5 STANDING
6 LAYING


#Measurements:

> featuresWanted.names
 [1] "tBodyAccMeanX"                "tBodyAccMeanY"               
 [3] "tBodyAccMeanZ"                "tBodyAccStdX"                
 [5] "tBodyAccStdY"                 "tBodyAccStdZ"                
 [7] "tGravityAccMeanX"             "tGravityAccMeanY"            
 [9] "tGravityAccMeanZ"             "tGravityAccStdX"             
[11] "tGravityAccStdY"              "tGravityAccStdZ"             
[13] "tBodyAccJerkMeanX"            "tBodyAccJerkMeanY"           
[15] "tBodyAccJerkMeanZ"            "tBodyAccJerkStdX"            
[17] "tBodyAccJerkStdY"             "tBodyAccJerkStdZ"            
[19] "tBodyGyroMeanX"               "tBodyGyroMeanY"              
[21] "tBodyGyroMeanZ"               "tBodyGyroStdX"               
[23] "tBodyGyroStdY"                "tBodyGyroStdZ"               
[25] "tBodyGyroJerkMeanX"           "tBodyGyroJerkMeanY"          
[27] "tBodyGyroJerkMeanZ"           "tBodyGyroJerkStdX"           
[29] "tBodyGyroJerkStdY"            "tBodyGyroJerkStdZ"           
[31] "tBodyAccMagMean"              "tBodyAccMagStd"              
[33] "tGravityAccMagMean"           "tGravityAccMagStd"           
[35] "tBodyAccJerkMagMean"          "tBodyAccJerkMagStd"          
[37] "tBodyGyroMagMean"             "tBodyGyroMagStd"             
[39] "tBodyGyroJerkMagMean"         "tBodyGyroJerkMagStd"         
[41] "fBodyAccMeanX"                "fBodyAccMeanY"               
[43] "fBodyAccMeanZ"                "fBodyAccStdX"                
[45] "fBodyAccStdY"                 "fBodyAccStdZ"                
[47] "fBodyAccMeanFreqX"            "fBodyAccMeanFreqY"           
[49] "fBodyAccMeanFreqZ"            "fBodyAccJerkMeanX"           
[51] "fBodyAccJerkMeanY"            "fBodyAccJerkMeanZ"           
[53] "fBodyAccJerkStdX"             "fBodyAccJerkStdY"            
[55] "fBodyAccJerkStdZ"             "fBodyAccJerkMeanFreqX"       
[57] "fBodyAccJerkMeanFreqY"        "fBodyAccJerkMeanFreqZ"       
[59] "fBodyGyroMeanX"               "fBodyGyroMeanY"              
[61] "fBodyGyroMeanZ"               "fBodyGyroStdX"               
[63] "fBodyGyroStdY"                "fBodyGyroStdZ"               
[65] "fBodyGyroMeanFreqX"           "fBodyGyroMeanFreqY"          
[67] "fBodyGyroMeanFreqZ"           "fBodyAccMagMean"             
[69] "fBodyAccMagStd"               "fBodyAccMagMeanFreq"         
[71] "fBodyBodyAccJerkMagMean"      "fBodyBodyAccJerkMagStd"      
[73] "fBodyBodyAccJerkMagMeanFreq"  "fBodyBodyGyroMagMean"        
[75] "fBodyBodyGyroMagStd"          "fBodyBodyGyroMagMeanFreq"    
[77] "fBodyBodyGyroJerkMagMean"     "fBodyBodyGyroJerkMagStd"     
[79] "fBodyBodyGyroJerkMagMeanFreq"